language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: bUbr2hIpHoecLlsEVVn7pUOeGTpDLh2DDGYzzt3Ie/e9o3653UeUHRxee5iYHUYOeV3gyjzrx5W5BGCVNkWUhEJlPvf8Qs6oi8paq9lgKsdnq9tRGaKoan0ycn7YpCEBqICKf9sItvwPNDpq2uhvPajwubvP54eUZbVjx00DXkSaTloCXtQYClszN4bbho4SYjHTiKLo9F7srCX/wZ/OKaJvN40sukjEDVql23uV2toLP5SjF9F3b7YOwJsOmoZM/a5fmV6Mc3c1T0LajuKYv5B7KNY0pJEAqhHK1wC1vRaJKuGuDwxio/zrO6E3EHHO8lNBkMKZlXkhs1j84y4UwOU7i/uRNMBg70sG98OFxPj83feUDHi3xRKAH310TnmEDyFklT2X3v7wd0XMzloWPTXKnfxHUwDB8E1bX+kJ6VjlnDlexnhVmj/hQf3G2lYXq8uY7LaOpIt8laWmbMxJ8yA9ciYITR3YiXCHlDCvVimXSPbh3Syv0pVtLhvJaPStabYjpqEkfr32EUQOrlevDD8U/U4lRnhVNG4sKkucZ1UW0XXQKhJqRjcqm5OMrMJQtjeuG5MUbKWI/XHy8RSPkRt15vmZIHy/x0mBoyMJJFyoTU6Mr29vrNW2Ms0ofvueCHPuR3A7sJrUUggptYAJJuBhjvk9XpknfRtGCyZgZmQ=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings .travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
- bash <(curl -s https://codecov.io/bash)
