---
name: release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          name: 'github'
          email: 'digitaal-techniek@vpro.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: mvn -Pdeploy --batch-mode  -Darguments=-DskipTests  release:prepare release:perform
        env:
          SONATYPE_USERNAME:  ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
